version: '3.1'

services:

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile_b
    image: docker.io/thefilmpulse/backend
    restart: always
    volumes:
      - "./backend:/app/backend"
    env_file:
      - dev.env
    ports:
      - "5000:5000"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"