# Use an official Python runtime as a parent image
FROM python:3.12.0-slim

# Set the working directory in the container
WORKDIR /app


RUN apt update

# Don't run pip install everytime code changes, do it only when requirements.txt changes
COPY backend/requirements.txt /app/backend/requirements.txt

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r /app/backend/requirements.txt

# Copy the backend files
COPY backend /app/backend

# Copy the entrypoint script into the container
COPY entrypoint.sh /app/entrypoint.sh

# Make the entrypoint script executable
RUN chmod +x /app/entrypoint.sh

# Expose port
EXPOSE 5000

# Define environment variable
ENV FLASK_APP=backend/app.py

# Set the entrypoint
ENTRYPOINT ["/app/entrypoint.sh"]