# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the backend files
COPY backend /app/backend

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r /app/backend/requirements.txt

# Expose port
EXPOSE 5000

# Define environment variable
ENV FLASK_APP=backend/app.py

# Run the Flask application on container startup
CMD ["flask", "run", "--host=0.0.0.0"]