# Use a Node.js image as a parent image
FROM node:alpine as builder

# Set the working directory in the container
WORKDIR /app/frontend

# Copy the frontend files
COPY frontend/package.json frontend/package-lock.json ./
COPY frontend/public ./public
COPY frontend/src ./src

# Install frontend dependencies
RUN npm install

# Build the frontend
RUN npm run build

# Use a lightweight Nginx image to serve the built frontend
FROM nginx:alpine

# Copy the built frontend files from the previous stage
COPY --from=builder /app/frontend/build /usr/share/nginx/html

# Expose port
EXPOSE 80

# Default command to run Nginx
CMD ["nginx", "-g", "daemon off;"]