"""Add columns in userOpinion and userPrediction to record user's winnings

Revision ID: 42259b5ead35
Revises: d06e209a52cf
Create Date: 2024-06-03 15:10:41.266691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42259b5ead35'
down_revision = 'd06e209a52cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_opinion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coins_won', sa.Integer(), nullable=True))

    with op.batch_alter_table('user_prediction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coins_won', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rank', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_prediction', schema=None) as batch_op:
        batch_op.drop_column('rank')
        batch_op.drop_column('coins_won')

    with op.batch_alter_table('user_opinion', schema=None) as batch_op:
        batch_op.drop_column('coins_won')

    # ### end Alembic commands ###
