"""Add user bans.

Revision ID: 6010b51e65f5
Revises: 
Create Date: 2024-05-16 05:59:12.291661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6010b51e65f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_banned', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_banned')

    # ### end Alembic commands ###
