"""Add columns in tables to prepare for processing result of opinions/predictions

Revision ID: d06e209a52cf
Revises: cde22260f422
Create Date: 2024-06-02 18:59:50.926741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd06e209a52cf'
down_revision = 'cde22260f422'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Finished', sa.Integer(), nullable=True))

    with op.batch_alter_table('opinion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correct_answer', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('Finished', sa.Integer(), nullable=True))

    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correct_answer', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('Finished', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.drop_column('Finished')
        batch_op.drop_column('correct_answer')

    with op.batch_alter_table('opinion', schema=None) as batch_op:
        batch_op.drop_column('Finished')
        batch_op.drop_column('correct_answer')

    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.drop_column('Finished')

    # ### end Alembic commands ###
