"""Add user email and full name fields

Revision ID: d21e7dee68c3
Revises: 6010b51e65f5
Create Date: 2024-05-17 02:37:20.272771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd21e7dee68c3'
down_revision = '6010b51e65f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('full_name', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('full_name')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
