"""Add terms field in voucher

Revision ID: e05575dcb3e2
Revises: 7d6e4407111b
Create Date: 2024-06-17 17:53:42.833563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e05575dcb3e2'
down_revision = '7d6e4407111b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voucher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terms', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voucher', schema=None) as batch_op:
        batch_op.drop_column('terms')

    # ### end Alembic commands ###
