"""Final switch to mean_value in prediction table

Revision ID: eee43b6f9555
Revises: 4c7b8ffae55b
Create Date: 2024-06-02 05:30:45.594811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eee43b6f9555'
down_revision = '4c7b8ffae55b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mean_value', sa.Float(), nullable=True))
        batch_op.drop_column('mean_prediction')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mean_prediction', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('mean_value')

    # ### end Alembic commands ###
